[book]
authors = ["Gijs Arkink"]
language = "en"
multilingual = false
src = "src"
title = "Process & safety Roboost"

[preprocessor.plantuml]
plantuml-cmd="http://localhost:8181"

[output.html]
defaulth-theme = "Ayu"